spring.application.name=docshund
spring.profiles.active=local
spring.profiles.include=API-KEY


spring.messages.basename=messages/alerts,messages/chats,messages/docs,messages/forums,messages/supports,messages/users,messages/global
