# Alerts Controller - Success Messages
alert.delete.success=\uC54C\uB9BC\uC774 \uC131\uACF5\uC801\uC73C\uB85C \uC0AD\uC81C\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
alert.delete.bulk.success=\uC54C\uB9BC\uC774 \uC77C\uAD04 \uC0AD\uC81C\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
alert.read.success=\uC54C\uB9BC\uC774 \uC77D\uC74C \uCC98\uB9AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
alert.read.bulk.success=\uC54C\uB9BC\uC774 \uC77C\uAD04 \uC77D\uC74C \uCC98\uB9AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4.

# Alerts Exception Messages
alert.error.userNotFound=\uD68C\uC6D0\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.
alert.error.userNotAuthorized=\uB85C\uADF8\uC778 \uC0C1\uD0DC\uAC00 \uC544\uB2D9\uB2C8\uB2E4.
alert.error.noPermission=\uAD00\uB9AC\uC790\uAC00 \uC544\uB2D9\uB2C8\uB2E4.
alert.error.notYourAlert=\uBCF8\uC778\uC758 \uC54C\uB9BC\uB9CC \uC77D\uAC70\uB098 \uC0AD\uC81C\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.
alert.error.alertNotFound=\uC54C\uB9BC\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.
alert.error.requiredIsEmpty=\uD544\uC218 \uC785\uB825\uAC12\uC774 \uB204\uB77D\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
alert.error.tooManyRequest=\uC694\uCCAD\uC774 \uB108\uBB34 \uB9CE\uC2B5\uB2C8\uB2E4.
alert.error.illegalArgument=\uC798\uBABB\uB41C \uC778\uC790\uAC70\uB098 \uD544\uC218 \uC778\uC790\uAC00 \uB204\uB77D\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
alert.error.alreadyRequested=\uC774\uBBF8 \uCC98\uB9AC\uB41C \uC791\uC5C5\uC785\uB2C8\uB2E4.
alert.error.unknownCategory=\uC54C \uC218 \uC5C6\uB294 \uC54C\uB9BC \uCE74\uD14C\uACE0\uB9AC\uC785\uB2C8\uB2E4.

# Alerts Service - Title & Content Messages
alert.title.translation.liked=\uD83E\uDD0E \uB0B4\uAC00 \uBC88\uC5ED\uD55C \uBB38\uC11C\uC5D0 \uC88B\uC544\uC694\uAC00 \uCD94\uAC00\uB418\uC5C8\uC5B4\uC694!
alert.content.translation.liked=[ {0} ] \uBB38\uC11C\uC5D0\uC11C \uBC88\uC5ED\uD55C \uBB38\uC7A5 ''{1}''\uC774(\uAC00) \uC88B\uC544\uC694\uB97C \uBC1B\uC558\uC2B5\uB2C8\uB2E4!
alert.title.article.commented=\uD83D\uDCAC \uB0B4 \uAC8C\uC2DC\uAE00\uC5D0 \uC0C8\uB85C\uC6B4 \uB313\uAE00\uC774 \uB2EC\uB838\uC5B4\uC694!
alert.content.article.commented=[ {0} ] \uC5D0 \uC0C8\uB85C\uC6B4 \uB313\uAE00\uC774 \uB2EC\uB838\uC2B5\uB2C8\uB2E4!
alert.title.comment.replied=\uD83D\uDCAC\uD83D\uDD04 \uB0B4 \uB313\uAE00\uC5D0 \uB300\uB313\uAE00\uC774 \uB2EC\uB838\uC5B4\uC694!
alert.content.comment.replied=\uB313\uAE00 [ {0} ] \uC5D0 \uC0C8\uB85C\uC6B4 \uB300\uB313\uAE00\uC774 \uB2EC\uB838\uC2B5\uB2C8\uB2E4!
alert.title.inquiry.answered=\uD83D\uDC8C \uBB38\uC758\uC5D0 \uB300\uD55C \uB2F5\uBCC0\uC774 \uB4F1\uB85D\uB418\uC5C8\uC2B5\uB2C8\uB2E4!
alert.content.inquiry.answered=\uB2F9\uC2E0\uC758 \uBB38\uC758 [ {0} ] \uC5D0 \uB300\uD55C \uB2F5\uBCC0\uC774 \uB4F1\uB85D\uB418\uC5C8\uC2B5\uB2C8\uB2E4!