# WebSocketExceptionCode Messages
chat.error.invalidPrincipal=\uCC44\uD305\uC744 \uC0AC\uC6A9\uD560 \uAD8C\uD55C\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.
chat.error.notFound=\uCC44\uD305\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.

# ChatController Success Messages
chat.status.update.success=\uBCC0\uACBD\uC774 \uC644\uB8CC\uB418\uC5C8\uC2B5\uB2C8\uB2E4.