# Forum Exception Messages
forums.error.invalidCategory=\uC874\uC7AC\uD558\uC9C0 \uC54A\uB294 \uCE74\uD14C\uACE0\uB9AC\uC785\uB2C8\uB2E4.
forums.error.mismatchArticle=\uB313\uAE00\uACFC \uAC8C\uC2DC\uAE00\uC758 \uC815\uBCF4\uAC00 \uC77C\uCE58\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.
forums.error.commentNotFound=\uD574\uB2F9 \uB313\uAE00\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.
forums.error.articleNotFound=\uD574\uB2F9 \uAC8C\uC2DC\uAE00\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.

# Comment Info DTO Messages
forums.comment.deleted=\uC0AD\uC81C\uB41C \uB313\uAE00
forums.comment.hidden=\uC228\uAE40 \uCC98\uB9AC\uB41C \uB313\uAE00
forums.comment.defaultNickname=\uBA4D\uBA4D\uC774

# Forum Controller Success Messages
forums.status.update.success=\uBCC0\uACBD\uC774 \uC644\uB8CC\uB418\uC5C8\uC2B5\uB2C8\uB2E4.
